#!/usr/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

ZULIP_VERSION="7.5"

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export DEBIAN_FRONTEND=noninteractive

echo "* Setup language env"
locale-gen en_US.utf8 || true

echo "* Get latest"
# add-apt-repository universe
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Disable and remove rpcbind"
apt-get -y remove rpcbind || true
systemctl stop rpcbind.service
systemctl disable rpcbind.service

echo "* Disable nfs-client"
systemctl unmask nfs-client.target
systemctl disable nfs-client.target

echo "* Disable ssh"
systemctl stop ssh
systemctl disable ssh

echo "* Download zulip"
cd /root
curl -fLO "https://download.qutic.com/src/zulip/zulip-server-${ZULIP_VERSION}.tar.gz"
tar -xf zulip-server-${ZULIP_VERSION}.tar.gz

echo "* Create bash-history"
cat >> /root/.bash_history << EOF
systemctl restart zulip
systemctl status zulip
systemctl edit --full zulip
systemctl daemon-reload
systemctl reset-failed zulip.service
systemctl reload nginx
journalctl --since $(date '+%Y-%m-%d')
EOF

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
rm /var/log/syslog || true
touch /var/log/syslog || true
rm /root/customize
history -c
